#include "FlightTaskFAPosition.hpp"

bool FlightTaskFAPosition::activate(const trajectory_setpoint_s &last_setpoint)
{
	if (!FlightTaskManualPosition::activate(last_setpoint)) {
		return false;
	}

	// FA-specific initialization can be added here later.
	// First version should keep activation behavior identical to ManualPosition.
	return true;
}

bool FlightTaskFAPosition::update()
{
	if (!FlightTaskManualPosition::update()) {
		return false;
	}

	applyFullyActuatedSetpointPolicy();
	return true;
}

void FlightTaskFAPosition::applyFullyActuatedSetpointPolicy()
{
	// First version policy:
	// 1. Keep position and velocity setpoints generated by ManualPosition.
	// 2. Keep yaw behavior generated by ManualPosition.
	// 3. Avoid generating a roll/pitch attitude command here.
	// 4. Let fa_pos_control convert trajectory_setpoint to 6-DoF wrench.

	// This function is intentionally minimal in the first version.
	// Add FA-specific constraints or setpoint annotations here later.
}