#!/bin/sh
#
# @name Gazebo f450 quadcopter
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=f450}

# Generic f450 quadcopter drone defaults
param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# Rotor 0: Front Right
param set-default CA_ROTOR0_PX 0.159
param set-default CA_ROTOR0_PY 0.159
param set-default CA_ROTOR0_KM  0.014

# Rotor 1: Back Left
param set-default CA_ROTOR1_PX -0.159
param set-default CA_ROTOR1_PY -0.159
param set-default CA_ROTOR1_KM  0.014

# Rotor 2: Front Left
param set-default CA_ROTOR2_PX 0.159
param set-default CA_ROTOR2_PY -0.159
param set-default CA_ROTOR2_KM -0.014

# Rotor 3: Back Right
param set-default CA_ROTOR3_PX -0.159
param set-default CA_ROTOR3_PY 0.159
param set-default CA_ROTOR3_KM -0.014

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2

# Override the Autostart ID
param set-default SYS_AUTOSTART 4022