#!/bin/sh
#
# @name Gazebo fy690s
#
# @type Hexarotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=fy690s}

param set-default MAV_TYPE 13
param set-default SIM_GZ_EN 1

# --- MULTICOPTER CONTROL ALLOCATION ---
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

# Rotor 0 (Front Left in SDF) - CCW
param set-default CA_ROTOR0_PX 0.298
param set-default CA_ROTOR0_PY -0.172
param set-default CA_ROTOR0_KM 0.05

# Rotor 1 (Center Left in SDF) - CCW
param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY -0.345
param set-default CA_ROTOR1_KM 0.05

# Rotor 2 (Rear Left in SDF) - CW
param set-default CA_ROTOR2_PX -0.298
param set-default CA_ROTOR2_PY -0.172
param set-default CA_ROTOR2_KM -0.05

# Rotor 3 (Rear Right in SDF) - CW
param set-default CA_ROTOR3_PX -0.298
param set-default CA_ROTOR3_PY 0.172
param set-default CA_ROTOR3_KM -0.05

# Rotor 4 (Center Right in SDF) - CCW
param set-default CA_ROTOR4_PX 0.0
param set-default CA_ROTOR4_PY 0.345
param set-default CA_ROTOR4_KM 0.05

# Rotor 5 (Front Right in SDF) - CW
param set-default CA_ROTOR5_PX 0.298
param set-default CA_ROTOR5_PY 0.172
param set-default CA_ROTOR5_KM -0.05

# --- GAZEBO MOTOR MAPPINGS ---
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000

param set-default SYS_AUTOSTART 6001
